
import { useState } from 'react';
import { Message } from '@/types/chat';

export const useChatMessages = () => {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      text: "Hi there! I'm GGD, your friendly AI assistant. I'm here to help you with BlogMate AI and answer any questions you might have. How can I assist you today? 😊",
      sender: 'ai',
      timestamp: new Date()
    }
  ]);
  const [isTyping, setIsTyping] = useState(false);

  const generateAIResponse = (userMessage: string): string => {
    const lowerMessage = userMessage.toLowerCase();
    
    // Friendly responses based on common queries
    if (lowerMessage.includes('hello') || lowerMessage.includes('hi') || lowerMessage.includes('hey')) {
      return "Hello! 👋 Great to see you here! I'm GGD, and I'm excited to help you make the most of BlogMate AI. What would you like to know?";
    }
    
    if (lowerMessage.includes('blog') && lowerMessage.includes('generate')) {
      return "Awesome! BlogMate AI can generate SEO-optimized blog posts in seconds! 🚀 Just enter your topic in the Blog Generator, and our AI will create a professional post with relevant images. Want me to guide you through the process?";
    }
    
    if (lowerMessage.includes('ad') || lowerMessage.includes('advertisement')) {
      return "Great question! 🎯 BlogMate AI has a powerful Ad Generator that creates engaging animated advertisements, especially for gaming content. You can customize colors, text, and style to match your brand perfectly!";
    }
    
    if (lowerMessage.includes('funnel') || lowerMessage.includes('sales')) {
      return "Perfect! Our Sales Funnel Generator is amazing! 💰 It creates professional sales pages with countdown timers, testimonials, and conversion optimization. You can build high-converting funnels in minutes!";
    }
    
    if (lowerMessage.includes('help') || lowerMessage.includes('how')) {
      return "I'm here to help! 😊 BlogMate AI has several powerful features: Blog Generator, Gaming Ads Creator, Sales Funnel Builder, and Ad Rotator. Which one interests you most? I can walk you through any of them!";
    }
    
    if (lowerMessage.includes('price') || lowerMessage.includes('cost') || lowerMessage.includes('free')) {
      return "Great news! 🎉 BlogMate AI offers a free tier to get you started! You can generate content and explore all features. For advanced features and higher limits, we have affordable premium plans. Want to start with the free version?";
    }
    
    if (lowerMessage.includes('seo')) {
      return "SEO is our specialty! 📈 Every blog post generated by BlogMate AI is automatically optimized for search engines with proper headings, meta descriptions, keywords, and structure. Your content will be ready to rank on Google!";
    }
    
    if (lowerMessage.includes('thank')) {
      return "You're so welcome! 😊 I'm thrilled I could help! That's what I'm here for - making your content creation journey smooth and successful. Feel free to ask me anything else anytime!";
    }
    
    // Default friendly response
    return "That's a great question! 🤔 I'm here to help you make the most of BlogMate AI. Whether you need help with blog generation, creating ads, building sales funnels, or managing content - I've got you covered! Could you tell me a bit more about what you're looking to achieve?";
  };

  const sendMessage = (inputText: string, onResponse: (response: string) => void) => {
    if (!inputText.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      text: inputText,
      sender: 'user',
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setIsTyping(true);

    // Simulate AI thinking time
    setTimeout(() => {
      const aiResponse = generateAIResponse(inputText);
      const aiMessage: Message = {
        id: (Date.now() + 1).toString(),
        text: aiResponse,
        sender: 'ai',
        timestamp: new Date()
      };

      setMessages(prev => [...prev, aiMessage]);
      setIsTyping(false);
      onResponse(aiResponse);
    }, 1000 + Math.random() * 1000);
  };

  return {
    messages,
    isTyping,
    sendMessage
  };
};
